name = "Magic"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4402fb0d17973ab01dc7a7ebb8b98c6dafd4ed4c0bce16503c5f2d6198177d5b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
