name = "world-gen"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "041f2a295d2f43716dd6ba92a3c678ea4bbb06382019997a23a97be78193bccf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
