name = "Create"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27a925201370e03f0b80f5b31385d799cc30e91d6eed10d9933ab1654887fe51"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
