name = "Apotheosis"
author = "runes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f96c3660ef7ba39d985c462d241eef73669d28597d1ef1fe10ef8128ff4f9ef6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
