name = "Magic"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d9dde3c3f5baa8fb41ac62e922642e0dc5477556ba1341f49e2de1d365384fd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
