name = "Magic"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4889ce8da91e4620a55c4c8d5cc857295c9561bc57d1a2d6f708c060af4188b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
