name = "Test101"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "970a997e069a5b4419db328c4e95ccfc97f4be84d34bd9a5909c09c72f721a12"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
