name = "Test101"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa5811c8401d16b598bc09003ac178d5afd7dd103f36645dd571535762aecfc2"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
