name = "Create"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b15b3bec2b486da47b721d5b1898bf019ccc4eb8e1f1fd47c910dc9264923b1e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
