name = "Food"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45041fa969ae3b27c233e579655e66212297c6f2662aaf0c8a10d0a890c20f05"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
