name = "Magic"
author = "DimPandora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3afcc74c173741039dbdb1320f7af6de80b22f47461f8bd3732fbbff1fd222c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
